//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Inventory_ProductType
    {
        public int IPT_ProductTypeID { get; set; }
        public string IPT_Code { get; set; }
        public string IPT_Name { get; set; }
        public bool IPT_IsActive { get; set; }
        public string IPT_Description { get; set; }
        public System.DateTime IPT_CreatedDate { get; set; }
        public int IPT_CreatedBy { get; set; }
        public Nullable<System.DateTime> IPT_UpdatedDate { get; set; }
        public Nullable<int> IPT_UpdatedBy { get; set; }
    }
}
