//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Customer_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_Customer_Type()
        {
            this.Tbl_Customers = new HashSet<Tbl_Customers>();
        }
    
        public byte CT_CustomerTypeID { get; set; }
        public string CT_Code { get; set; }
        public string CT_Name { get; set; }
        public string CT_Description { get; set; }
        public Nullable<bool> CT_IsActive { get; set; }
        public Nullable<System.DateTime> CT_CreatedDate { get; set; }
        public Nullable<int> CT_CreatedBy { get; set; }
        public Nullable<System.DateTime> CT_UpdatedDate { get; set; }
        public Nullable<int> CT_UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customers> Tbl_Customers { get; set; }
    }
}
