//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Customer_AddressType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_Customer_AddressType()
        {
            this.Tbl_Customer_Address = new HashSet<Tbl_Customer_Address>();
        }
    
        public int CAT_AddressTypeID { get; set; }
        public string CAT_Code { get; set; }
        public string CAT_Name { get; set; }
        public string CAT_Description { get; set; }
        public bool CAT_IsActive { get; set; }
        public System.DateTime CAT_CreatedDate { get; set; }
        public int CAT_CreatedBy { get; set; }
        public Nullable<System.DateTime> CAT_UpdatedDate { get; set; }
        public Nullable<int> CAT_UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customer_Address> Tbl_Customer_Address { get; set; }
    }
}
