//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inventory_ProductCategories
    {
        public int IPC_ProductCategoriesID { get; set; }
        public int IPC_IP_ProductID { get; set; }
        public int IPC_IC_CategoryID { get; set; }
    
        public virtual Tbl_Inventory_Category Tbl_Inventory_Category { get; set; }
        public virtual Tbl_Inventory_Products Tbl_Inventory_Products { get; set; }
    }
}
