//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sales_OrderItems
    {
        public int SOI_SalesOrderLineID { get; set; }
        public int SOI_SO_SalesOrderID { get; set; }
        public Nullable<int> SOI_ShoppingBasketDetailID { get; set; }
        public Nullable<int> SOI_IP_ProductID { get; set; }
        public string SOI_SKU { get; set; }
        public string SOI_ProductName { get; set; }
        public decimal SOI_Price { get; set; }
        public int SOI_Qty { get; set; }
        public Nullable<decimal> SOI_VatRate { get; set; }
        public decimal SOI_VatAmount { get; set; }
        public Nullable<decimal> SOI_DiscountAmt { get; set; }
        public decimal SOI_TotalNetAmt { get; set; }
        public bool SOI_IsReserved { get; set; }
        public Nullable<decimal> SOI_ShippingAmt { get; set; }
        public Nullable<System.DateTime> SOI_CreatedDate { get; set; }
        public Nullable<int> SOI_CreatedBy { get; set; }
        public Nullable<System.DateTime> SOI_UpdatedDate { get; set; }
        public Nullable<int> SOI_UpdatedBy { get; set; }
        public byte[] SOI_TimeStamp { get; set; }
        public string SOI_TaxCode { get; set; }
    
        public virtual Tbl_Sales_Orders Tbl_Sales_Orders { get; set; }
    }
}
