//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ExceptionLogger
    {
        public long ExcLog_Id { get; set; }
        public Nullable<System.Guid> ExcLog_ExceptionId { get; set; }
        public string ExcLog_ExceptionMessage { get; set; }
        public string ExcLog_ExceptionType { get; set; }
        public string ExcLog_ExceptionSource { get; set; }
        public string ExcLog_Url { get; set; }
        public Nullable<System.DateTime> ExcLog_LogDate { get; set; }
        public Nullable<bool> ExcLog_IsResolved { get; set; }
        public Nullable<bool> ExcLog_IsActive { get; set; }
        public Nullable<System.DateTime> ExcLog_CreatedDate { get; set; }
        public Nullable<int> ExcLog_CreatedBy { get; set; }
        public Nullable<System.DateTime> ExcLog_UpdatedDate { get; set; }
        public Nullable<int> ExcLog_UpdatedBy { get; set; }
    }
}
