//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inventory_CategoryType
    {
        public int ICT_CategoryTypeID { get; set; }
        public Nullable<int> ICT_ReportingCategoryID { get; set; }
        public string ICT_CategoryName { get; set; }
        public Nullable<int> ICT_CategoryID { get; set; }
        public Nullable<bool> ICT_IsActive { get; set; }
        public Nullable<System.DateTime> ICT_CreatedOn { get; set; }
        public Nullable<int> ICT_CreatedBy { get; set; }
        public Nullable<System.DateTime> ICT_UpdatedOn { get; set; }
        public Nullable<int> ICT_UpdatedBy { get; set; }
    }
}
