//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inventory_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Inventory_Products()
        {
            this.Tbl_Inventory_ProductCategories = new HashSet<Tbl_Inventory_ProductCategories>();
        }
    
        public int IP_ProductID { get; set; }
        public int IP_IC_CategoryID { get; set; }
        public string IP_SKU { get; set; }
        public string IP_ProductName { get; set; }
        public string IP_ImageName { get; set; }
        public string IP_Sizeable { get; set; }
        public Nullable<decimal> IP_CostPrice { get; set; }
        public Nullable<decimal> IP_HighPrice { get; set; }
        public Nullable<decimal> IP_MediumPrice { get; set; }
        public Nullable<decimal> IP_LowPrice { get; set; }
        public Nullable<decimal> IP_StartPrice { get; set; }
        public Nullable<decimal> IP_TargetPrice { get; set; }
        public Nullable<decimal> IP_Margin { get; set; }
        public string IP_Brand { get; set; }
        public string IP_Remark { get; set; }
        public Nullable<bool> IP_IsActive { get; set; }
        public int IP_CreatedBy { get; set; }
        public System.DateTime IP_CreatedDate { get; set; }
        public Nullable<int> IP_UpdatedBy { get; set; }
        public Nullable<System.DateTime> IP_UpdatedDate { get; set; }
        public Nullable<decimal> IP_ClearancePrice { get; set; }
        public byte[] IP_TimeStamp { get; set; }
        public string IP_TaxCode { get; set; }
        public string IP_ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Inventory_ProductCategories> Tbl_Inventory_ProductCategories { get; set; }
    }
}
