//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customer_Address
    {
        public int CA_AddressID { get; set; }
        public int CA_C_CustomerID { get; set; }
        public int CA_AddressTypeID { get; set; }
        public string CA_Address1 { get; set; }
        public string CA_Address2 { get; set; }
        public string CA_Address3 { get; set; }
        public string CA_Address4 { get; set; }
        public string CA_Locality { get; set; }
        public string CA_Area { get; set; }
        public string CA_Town { get; set; }
        public Nullable<int> CA_CountryID { get; set; }
        public string CA_PostCode { get; set; }
        public Nullable<int> CA_StatusID { get; set; }
        public Nullable<bool> CA_IsDefaultAddress { get; set; }
        public System.DateTime CA_CreatedDate { get; set; }
        public Nullable<int> CA_CreatedBy { get; set; }
        public Nullable<System.DateTime> CA_UpdatedDate { get; set; }
        public Nullable<int> CA_UpdatedBy { get; set; }
        public Nullable<int> CA_StateID { get; set; }
        public Nullable<bool> CA_IsDeleted { get; set; }
        public byte[] CA_TimeStamp { get; set; }
    
        public virtual Mst_Customer_AddressType Mst_Customer_AddressType { get; set; }
        public virtual System_MstCountry System_MstCountry { get; set; }
        public virtual System_MstState System_MstState { get; set; }
        public virtual System_MstStatus System_MstStatus { get; set; }
        public virtual Tbl_Customers Tbl_Customers { get; set; }
    }
}
