//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sales_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sales_Orders()
        {
            this.Tbl_Sales_OrderItems = new HashSet<Tbl_Sales_OrderItems>();
        }
    
        public int SO_SalesOrderID { get; set; }
        public string SO_SalesOrderCode { get; set; }
        public int SO_C_CustomerID { get; set; }
        public Nullable<bool> SO_IsVatable { get; set; }
        public Nullable<decimal> SO_TotalVatAmt { get; set; }
        public Nullable<decimal> SO_VatRate { get; set; }
        public Nullable<decimal> SO_TotalDiscountAmt { get; set; }
        public Nullable<decimal> SO_TotalGrossAmount { get; set; }
        public Nullable<decimal> SO_TotalNetAmount { get; set; }
        public Nullable<decimal> SO_ShippingCharges { get; set; }
        public Nullable<int> SO_StatusID { get; set; }
        public Nullable<bool> SO_IsOnHold { get; set; }
        public Nullable<System.DateTime> SO_HoldDate { get; set; }
        public Nullable<int> SO_HoldBy { get; set; }
        public string SO_CancelReason { get; set; }
        public Nullable<int> SO_ShippingMethodID { get; set; }
        public Nullable<decimal> SO_VoucherAmt { get; set; }
        public Nullable<int> SO_ShippingSchemeID { get; set; }
        public System.DateTime SO_OrderDate { get; set; }
        public Nullable<System.DateTime> SO_DispatchDate { get; set; }
        public Nullable<System.DateTime> SO_CreatedDate { get; set; }
        public Nullable<int> SO_CreatedBy { get; set; }
        public Nullable<System.DateTime> SO_UpdatedDate { get; set; }
        public Nullable<int> SO_UpdatedBy { get; set; }
        public Nullable<System.DateTime> SO_CancelDate { get; set; }
        public Nullable<int> SO_CancelBy { get; set; }
        public Nullable<int> SO_ShippingAddressID { get; set; }
        public Nullable<int> SO_BillingAddressID { get; set; }
        public Nullable<decimal> SO_OrderDiscountAmt { get; set; }
        public Nullable<int> SO_PaymentGatewayID { get; set; }
        public Nullable<bool> SO_IsPriority { get; set; }
        public Nullable<int> SO_CancelReasonId { get; set; }
        public Nullable<bool> SO_IsPaymentReceived { get; set; }
        public string SO_DeviceType { get; set; }
        public string SO_DeviceName { get; set; }
        public byte[] SO_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sales_OrderItems> Tbl_Sales_OrderItems { get; set; }
    }
}
