//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeledhaage.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inventory_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Inventory_Category()
        {
            this.Tbl_Inventory_ProductCategories = new HashSet<Tbl_Inventory_ProductCategories>();
        }
    
        public int IC_CategoryID { get; set; }
        public Nullable<int> IC_ParentID { get; set; }
        public string IC_Name { get; set; }
        public string IC_Description { get; set; }
        public bool IC_IsActive { get; set; }
        public System.DateTime IC_CreatedDate { get; set; }
        public int IC_CreatedBy { get; set; }
        public Nullable<int> IC_UpdatedBy { get; set; }
        public Nullable<System.DateTime> IC_UpdatedDate { get; set; }
        public string IC_Slug { get; set; }
        public Nullable<int> IC_Sorting { get; set; }
        public Nullable<int> Ic_OrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Inventory_ProductCategories> Tbl_Inventory_ProductCategories { get; set; }
    }
}
